### ISSUE TITLE
Allow toggling of the fixes/Text config

### ISSUE THREAD

**Issue by wd4q5dy** [hamarb123/MCMacOSInputFixes#13]
mainly because I use the control + left click = right click function to bridge quickly

**Comment by hamarb123** [comment]
I think it's better to not include this since I definitely consider it a bug/fault personally, because it means you simply cannot do many things while using the default sprint key, like attacking. I think you should either invest in a mouse which has a right click button, or look into remapping input combinations using an external application like Karabiner. I will consider it further, but I'm not particularly keen on including this option.

**Comment by Compsogbrickus** [comment]
Hello! I've been using an edited version of this mod for a bit, and decided to see if there were any similar comments on control + left click. I've been playing MC with a trackpad since I bought the game in late 2013, and control click has been amazingly helpful for me. I really like your scrolling fixes from this mod, but I've had to manually disable your control click "fix" so I can reasonably play the game.

Remapping input combinations with an external application is not a valid solution. It leads to issues with input locking, and I've had enough experience with a few other games that also "fix" control click to know how problematic this is.

I can go more into detail if you would like. It would be really cool to see an option to toggle the control click bugfix!

**Comment by hamarb123** [comment]
I'll consider adding this in the next version, will let you know when it's released.

**Comment by hamarb123** [comment]
Fixed in 1.6
