### ISSUE TITLE
Crash during Initialization w/ 'Think Same' MCv1.19.2

### ISSUE THREAD

**Issue by Happenstance-14** [hamarb123/MCMacOSInputFixes#28]
Expectable conflict w/ '[Think Same](https://modrinth.com/mod/think-same)' running Quilt or Fabric, I imagine some feature overlap.  Crash report attached below generated running Quilt.

[crash-2024-06-09_16.01.07-client.txt](https://github.com/user-attachments/files/15754493/crash-2024-06-09_16.01.07-client.txt)

Running Windows 11 (looking out for the silly Mac friends running my modlist!)

- Quilt 0.26.0  |  Fabric 0.15.11
- QFAPI 4.0.0-beta.30 + QSL 3.0.0-beta.29 w/ FAPI 0.77.0  |  FAPI 0.77.0
- MacOS Input Fixes 1.6
- Think Same 1.1.1

Tried to submit a report to Think Same, but the [repo's hosted on Forgejo](https://git.pfaff.dev/michael/thinksame.mc) & won't let me register an account. _[sigh]_
Messages open.

**Comment by hamarb123** [comment]
<img width="1656" alt="image" src="https://github.com/hamarb123/MCMacOSInputFixes/assets/25316035/5528cfc8-825a-4843-93f9-b67362a11450">

My mod fixes the first 2 as well, and the third seems to be an unintended side effect in the way their mod is done (which my mod doesn't touch iirc).

It seems like there is not much point to having their mod if you already have my mod, since mine fixes everything theirs does & more.

Please lmk if you'd like me to investigate further, but it seems to me like just removing Think Same would be the logical solution.
